name: CI/CD
on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:
  workflow_dispatch:

jobs:
  dispatcher:
    runs-on: ubuntu-24.04
    if: >-
      github.repository_owner == 'unibo-oop-projects' && (
        github.event_name != 'pull_request'
        || github.event.pull_request.head.repo.full_name != github.repository
        || contains(github.head_ref, 'dependabot')
      )
    steps:
      - run: 'true'
  ci-cd:
    permissions:
      contents: write
    needs:
      - dispatcher
    uses: ./.github/workflows/build-and-deploy.yml
    secrets: inherit
